services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: senacauto_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_pass123
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@senacauto.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass123
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db  # Corrigido para depender do serviço db

volumes:
  db-data: 

networks:
  pg-network:
    driver: bridge